/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase05;

import javax.swing.DefaultListModel;

/**
 *
 * @author Administrador
 */
public class ForGUI extends javax.swing.JFrame {

    /**
     * Creates new form ForGUI
     */
    public ForGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        lblFin = new javax.swing.JLabel();
        lblPaso = new javax.swing.JLabel();
        btnGenerarLista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFor = new javax.swing.JList<>();
        slideInicio = new javax.swing.JSlider();
        slideFin = new javax.swing.JSlider();
        slidePaso = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Inicio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setText("Fin");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setText("Paso");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblInicio.setText("0");
        getContentPane().add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        lblFin.setText("6");
        getContentPane().add(lblFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        lblPaso.setText("1");
        getContentPane().add(lblPaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        btnGenerarLista.setText("Generar lista");
        btnGenerarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarListaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jScrollPane1.setViewportView(listaFor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 140, -1));

        slideInicio.setMaximum(5);
        slideInicio.setToolTipText("");
        slideInicio.setValue(0);
        slideInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slideInicioStateChanged(evt);
            }
        });
        getContentPane().add(slideInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        slideFin.setMaximum(20);
        slideFin.setMinimum(6);
        slideFin.setValue(6);
        slideFin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slideFinStateChanged(evt);
            }
        });
        getContentPane().add(slideFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        slidePaso.setMaximum(4);
        slidePaso.setMinimum(1);
        slidePaso.setValue(1);
        slidePaso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slidePasoStateChanged(evt);
            }
        });
        getContentPane().add(slidePaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slideInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slideInicioStateChanged
        // TODO add your handling code here:
        //System.out.println(slideInicio.getValue());
        int i = slideInicio.getValue();
        lblInicio.setText(Integer.toString(i));
        
    }//GEN-LAST:event_slideInicioStateChanged

    private void slideFinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slideFinStateChanged
        // TODO add your handling code here:
         int f = slideFin.getValue();
         lblFin.setText(Integer.toString(f));
    }//GEN-LAST:event_slideFinStateChanged

    private void slidePasoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slidePasoStateChanged
        // TODO add your handling code here:
        int p = slidePaso.getValue();
        lblPaso.setText(Integer.toString(p));
    }//GEN-LAST:event_slidePasoStateChanged

    private void btnGenerarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarListaActionPerformed
        // TODO add your handling code here:
        int i = slideInicio.getValue();
        int f = slideFin.getValue();
        int p = slidePaso.getValue();
        
        DefaultListModel lista = new DefaultListModel();
        
        for(int c = i; c <= f; c += p){
            //System.out.println(c);
            lista.addElement(c);
        }
        
        listaFor.setModel(lista);
        
    }//GEN-LAST:event_btnGenerarListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFin;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblPaso;
    private javax.swing.JList<String> listaFor;
    private javax.swing.JSlider slideFin;
    private javax.swing.JSlider slideInicio;
    private javax.swing.JSlider slidePaso;
    // End of variables declaration//GEN-END:variables
}
