/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase09;

import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author Administrador
 */
public class GuiVector extends javax.swing.JFrame {
    int[] datos = new int[5];
    int posicion;
    DefaultListModel lista = new DefaultListModel();
    
    /**
     * Creates new form GuiVector
     */
    public GuiVector() {
        initComponents();
        posicion = 0;
        // traslada la información del arreglo a la lista 
        lista.removeAllElements();
        for (int i = 0; i < datos.length; i++) {
            lista.addElement(datos[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        jsValorEntrada = new javax.swing.JSpinner();
        lblPosicion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistValores = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 80, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 80, -1));

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 80, -1));
        getContentPane().add(jsValorEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 80, 30));

        lblPosicion.setText("vector[0]");
        getContentPane().add(lblPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 100, -1));

        jlistValores.setModel(lista);
        jlistValores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlistValoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlistValores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 70, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlistValoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistValoresMouseClicked
        // TODO add your handling code here:
        posicion = jlistValores.getSelectedIndex();
        lblPosicion.setText("vector[" + posicion + "]");
    }//GEN-LAST:event_jlistValoresMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        datos[posicion] = Integer.parseInt(jsValorEntrada.getValue().toString());
        
        // traslada la información del arreglo a la lista 
        lista.removeAllElements();
        for (int i = 0; i < datos.length; i++) {
            lista.addElement(datos[i]);
        }
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        datos[posicion] = 0;
        
        // traslada la información del arreglo a la lista 
        lista.removeAllElements();
        for (int i = 0; i < datos.length; i++) {
            lista.addElement(datos[i]);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        // TODO add your handling code here:
        Arrays.sort(datos);
        // traslada la información del arreglo a la lista 
        lista.removeAllElements();
        for (int i = 0; i < datos.length; i++) {
            lista.addElement(datos[i]);
        }
    }//GEN-LAST:event_btnOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiVector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlistValores;
    private javax.swing.JSpinner jsValorEntrada;
    private javax.swing.JLabel lblPosicion;
    // End of variables declaration//GEN-END:variables
}
